TLS Custom Private Key Resource
opencredo/terraform-provider-fastly pull request #70
Opened 2021-01-19 12:10 UTC by bengesoff

First draft of resource. Some tweaks probably needed

2021-01-19 12:16 UTC, wjam commented on fastly/provider.go
> +			"fastly_tls_private_key":                    resourceTLSPrivateKeyV1(),
The pattern for the naming of these functions would be the name of the resource without the provider prefix - 'fastly' in this case - in camel case rather than snake. This should be just `resourceTLSPrivateKey`

2021-01-19 12:17 UTC, wjam commented on fastly/resource_tls_private_key.go
> +			"created_at": {
Missing `Description` on these computed items

2021-01-19 12:17 UTC, wjam commented on fastly/resource_tls_private_key.go
> +	err = d.Set("name", privateKey.Name)
err should be checked if it not nil on each call to `Set`

2021-01-19 12:18 UTC, wjam commented
You will also need to update the contents of the `website/` directory

2021-01-19 12:19 UTC, bengesoff commented on fastly/provider.go
> +			"fastly_tls_private_key":                    resourceTLSPrivateKeyV1(),
So you mean skip the pattern of sticking the `V1` at the end?
```suggestion
			"fastly_tls_private_key":                    resourceTLSPrivateKey(),
```

2021-01-19 13:22 UTC, wjam commented on fastly/provider.go
> +			"fastly_tls_private_key":                    resourceTLSPrivateKeyV1(),
Yep - example: https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/provider.go#L404. The only examples I can think which break this pattern is this, due to how `aws_lb` and `aws_alb` are interchangeable: https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/provider.go#L1062-L1063

2021-01-19 13:49 UTC, trentrosenbaum requested changes
Looks to be going in the right direction with the comments and changes.  We have the test covering the create and import.  I would like to see the website docs.  The following can be used to confirm the render of the pages https://registry.terraform.io/tools/doc-preview

2021-01-19 13:49 UTC, trentrosenbaum commented on fastly/resource_tls_private_key.go
> +func resourceTLSPrivateKeyV1() *schema.Resource {
I think from the first suggested change in the fastly/provider.go the V1 will be removed from this function?

2021-01-19 13:49 UTC, trentrosenbaum commented on fastly/resource_tls_private_key.go
> +func resourceTLSPrivateKeyV1Create(d *schema.ResourceData, meta interface{}) error {
Again same here of the v1 removal and the other functions below.

2021-01-19 13:59 UTC, bengesoff commented on fastly/provider.go
> +			"fastly_tls_private_key":                    resourceTLSPrivateKeyV1(),
Ok thanks, I'll push that in a bit. Out of interest is there a reason the other resources have the V1 on them or is that just a pattern we're trying to move away from?

2021-01-20 08:37 UTC, wjam commented on fastly/resource_tls_private_key_test.go
> +	name := acctest.RandString(10)
The name should have the prefix `tf-test-` to make it easy to identify any resources that were leaked from running the acceptance tests

2021-01-20 08:46 UTC, bengesoff commented on fastly/resource_tls_private_key_test.go
> +	name := acctest.RandString(10)
Ah yes great point, thanks

2021-01-20 12:30 UTC, trentrosenbaum approved these changes

2021-01-20 12:34 UTC, merged