Implement `tls_configuration` data source
opencredo/terraform-provider-fastly pull request #71
Opened 2021-01-19 14:19 UTC by wjam

2021-01-19 14:53 UTC, bengesoff requested changes
Minor points about naming mainly, otherwise looks sweet

2021-01-19 14:53 UTC, bengesoff commented on fastly/data_source_tls_configuration.go
> +			"tls_service": {
I know there's a few questions to be answered around the PlatformTLS product anyway, but in the mean time, the use of "service" here could be misleading, especially with the API returning a `relationships.service` field referring to something different. I don't have a good alternative but some ideas could be:

- `platform_tls`: bool - not specifying it would default to the more common option of false
- `bulk`: bool - consistent with the API docs but still confusing what it actually does

2021-01-19 14:53 UTC, bengesoff commented on fastly/data_source_tls_configuration.go
> +	pageNumber := 0
Maybe calling this `cursor` or similar would make it more obvious that the page number isn't actually a page number? (as you found out the hard way 😏)

2021-01-19 14:53 UTC, bengesoff commented on fastly/data_source_tls_configuration_test.go
> +					resource.TestCheckResourceAttrSet("data.fastly_tls_configuration.subject", "bulk"),
Think this might need updating

2021-01-19 14:54 UTC, wjam commented on fastly/data_source_tls_configuration.go
> +			"tls_service": {
Can't be boolean as you can't tell the difference between not set and set to false. TLS Service comes from the Fastly documentation - https://developer.fastly.com/reference/api/tls/

2021-01-19 15:16 UTC, bengesoff commented on fastly/data_source_tls_configuration.go
> +			"tls_service": {
I see what you mean, I was just looking at the docs for the configuration itself (https://developer.fastly.com/reference/api/tls/custom-certs/configuration/) and thought "service" was a pretty overloaded word already. Let's leave it as is and if anyone else thinks it's misleading then we can take another look.

2021-01-20 09:28 UTC, bengesoff commented on fastly/data_source_tls_configuration.go
> +	cursor := 0
Did you find that zero-indexing the page number worked? For the `ListPrivateKeys` I have a suspicion that the first call ignores the 0 and requests the default "no offset" case, then the second call requests "page 1" which is the same result as the first. Curious if this behaviour is consistent across the endpoints

2021-01-20 09:52 UTC, wjam commented on fastly/data_source_tls_configuration.go
> +	cursor := 0
Zero indexing did work. The behaviour I saw was:
1. The first call, using 0 pageNumber, returned 2 items
2. The second call, using 1 pageNumber, returned 1 item - which was the second item from the first call.
3. The third call, using 2 pageNumber, returned no items

2021-01-20 10:22 UTC, bengesoff commented on fastly/data_source_tls_configuration.go
> +	cursor := 0
Does that mean that depending whether your target configuration is the first or second item, you might accidentally grab it twice?

2021-01-20 10:25 UTC, bengesoff commented on fastly/data_source_tls_configuration.go
> +	cursor := 0
I might be wrong but I think it should be like this:
```suggestion
	cursor := 1
```

2021-01-20 10:50 UTC, wjam commented on fastly/data_source_tls_configuration.go
> +	cursor := 0
No, that would skip the first item. The behaviour of `pageNumber` in the TLS configuration listing endpoint appears to be just controlling the `OFFSET`.

2021-01-20 11:01 UTC, bengesoff commented on fastly/data_source_tls_configuration.go
> +	cursor := 0
Good point... but even so - if the second item passes your filter functions you still risk adding it to your `configurations` slice twice do you not?

2021-01-20 11:04 UTC, bengesoff commented on fastly/data_source_tls_configuration.go
> +	cursor := 0
Wait actually I think the code is correct, but I'm getting hung up on this - the second call will use 2 pageNumber won't it

> 2. The second call, using 1 pageNumber, returned 1 item - which was the second item from the first call.

2021-01-20 11:15 UTC, wjam commented on fastly/data_source_tls_configuration.go
> +	cursor := 0
Yes, which appears to return all items _after_ the second configuration. The behaviour I described above was the _original_ implementation based solely on the API documentation.

The behaviour now implemented is:
1. The first call, using 0 pageNumber, returns 2 items
2. The second call, using 2 pageNumber, returns no items

2021-01-20 11:50 UTC, wjam commented
Closing to change destination

2021-01-20 11:50 UTC, closed without merging